# .sops.yaml
creation_rules:
  - path_regex: .*/cluster-secrets\.yaml$
    encrypted_regex: "^(data|stringData)$"
    age: age1e9dfma2zwf3t3pn6g354wasw3s7rlkn3ceqvpd0fvv5m2w6zuvzsjtra68
  - path_regex: .*/secrets\.yaml$
    encrypted_regex: "^(data|stringData)$"
    age: age1e9dfma2zwf3t3pn6g354wasw3s7rlkn3ceqvpd0fvv5m2w6zuvzsjtra68